#!/usr/bin/env python3
"""Inject and verify per-page SEO / social metadata for the manual site.

Each public HTML page gets a generated block between

    <!-- seo:begin (generated by .github/scripts/build_seo.py) -->
    ...
    <!-- seo:end -->

placed just before </head>. The block carries the canonical URL, favicon and
web-app manifest links, Open Graph / Twitter card tags and JSON-LD structured
data. The visible <title> and <meta name="description"> already present on the
page stay the single source of truth; this script only mirrors them into the
machine-readable tags.

Usage:
    python .github/scripts/build_seo.py            # rewrite pages in place
    python .github/scripts/build_seo.py --check    # fail if any page is stale
"""

from __future__ import annotations

import argparse
import json
import posixpath
import re
import sys
from html import escape, unescape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SITE_ORIGIN = "https://plc-console.fa-labo.com"
SITE_NAME = "FA Labo PLC Console 操作マニュアル"
APP_NAME = "FA Labo PLC Console"
APP_STORE_URL = "https://apps.apple.com/jp/app/fa-labo-plc-console/id6783619471"
OG_IMAGE = f"{SITE_ORIGIN}/assets/images/og-cover.png"
OG_IMAGE_W, OG_IMAGE_H = 1200, 630

BEGIN = "<!-- seo:begin (generated by .github/scripts/build_seo.py) -->"
END = "<!-- seo:end -->"
# Matches the block exactly as apply() inserts it: a newline, two-space indent,
# the begin marker, the body, and the end marker. Nothing outside is consumed,
# so strip + re-insert is a fixed point.
BLOCK_RE = re.compile(r"\n  " + re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)

TITLE_RE = re.compile(r"<title>(.*?)</title>", re.DOTALL | re.IGNORECASE)
DESC_RE = re.compile(
    r'<meta\s+name="description"\s+content="([^"]*)"\s*/?>', re.IGNORECASE
)
BREADCRUMB_RE = re.compile(
    r'<nav[^>]*class="breadcrumb"[^>]*>(.*?)</nav>', re.DOTALL | re.IGNORECASE
)
CRUMB_LINK_RE = re.compile(r'<a[^>]*href="([^"]+)"[^>]*>(.*?)</a>', re.DOTALL | re.IGNORECASE)
CRUMB_CURRENT_RE = re.compile(
    r'<span[^>]*aria-current="page"[^>]*>(.*?)</span>', re.DOTALL | re.IGNORECASE
)
TAG_RE = re.compile(r"<[^>]+>")


def pages() -> list[Path]:
    return sorted(
        p for p in ROOT.rglob("*.html")
        if "templates" not in p.relative_to(ROOT).parts
    )


def rel_url(page: Path) -> str:
    rel = page.relative_to(ROOT).as_posix()
    if rel == "index.html":
        return f"{SITE_ORIGIN}/"
    return f"{SITE_ORIGIN}/{rel}"


def base_prefix(page: Path) -> str:
    depth = len(page.relative_to(ROOT).parent.parts)
    return "../" * depth


def plain_text(fragment: str) -> str:
    return unescape(TAG_RE.sub("", fragment)).strip()


def resolve_url(page: Path, href: str) -> str:
    page_dir = "/" + page.relative_to(ROOT).parent.as_posix()
    if page_dir == "/.":
        page_dir = "/"
    joined = posixpath.normpath(posixpath.join(page_dir, href))
    if joined == "/index.html":
        joined = "/"
    return f"{SITE_ORIGIN}{joined}"


def breadcrumb_items(page: Path, source: str, canonical: str) -> list[tuple[str, str | None]]:
    match = BREADCRUMB_RE.search(source)
    items: list[tuple[str, str | None]] = []
    if match:
        block = match.group(1)
        for href, label in CRUMB_LINK_RE.findall(block):
            items.append((plain_text(label), resolve_url(page, href)))
        current = CRUMB_CURRENT_RE.search(block)
        if current:
            items.append((plain_text(current.group(1)), canonical))
    if not items:
        items = [("トップ", f"{SITE_ORIGIN}/")]
    return items


def json_ld_script(data: object) -> str:
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    payload = payload.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    return f'  <script type="application/ld+json">{payload}</script>'


def structured_data(page: Path, source: str, canonical: str, title: str, desc: str) -> list[str]:
    rel = page.relative_to(ROOT).as_posix()
    if rel == "404.html":
        return []
    if rel == "index.html":
        website = {
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": SITE_NAME,
            "url": f"{SITE_ORIGIN}/",
            "inLanguage": "ja",
            "publisher": {"@type": "Organization", "name": "FA Labo"},
            "potentialAction": {
                "@type": "SearchAction",
                "target": {
                    "@type": "EntryPoint",
                    "urlTemplate": f"{SITE_ORIGIN}/search.html?q={{search_term_string}}",
                },
                "query-input": "required name=search_term_string",
            },
        }
        app = {
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": APP_NAME,
            "operatingSystem": "Android, iOS",
            "applicationCategory": "BusinessApplication",
            "description": desc,
            "url": f"{SITE_ORIGIN}/",
            "downloadUrl": APP_STORE_URL,
            "image": OG_IMAGE,
            "inLanguage": "ja",
            "offers": {"@type": "Offer", "category": "paid"},
            "publisher": {"@type": "Organization", "name": "FA Labo"},
        }
        return [json_ld_script(website), json_ld_script(app)]

    headline = title.split(" | ", 1)[0].strip() or title
    crumbs = breadcrumb_items(page, source, canonical)
    breadcrumb = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": i + 1,
                "name": name,
                **({"item": url} if url else {}),
            }
            for i, (name, url) in enumerate(crumbs)
        ],
    }
    article = {
        "@context": "https://schema.org",
        "@type": "TechArticle",
        "headline": headline,
        "description": desc,
        "inLanguage": "ja",
        "url": canonical,
        "image": OG_IMAGE,
        "isPartOf": {"@type": "WebSite", "name": SITE_NAME, "url": f"{SITE_ORIGIN}/"},
        "publisher": {"@type": "Organization", "name": "FA Labo"},
    }
    return [json_ld_script(breadcrumb), json_ld_script(article)]


def build_block(page: Path, source: str) -> str:
    rel = page.relative_to(ROOT).as_posix()
    is_index = rel == "index.html"
    is_404 = rel == "404.html"

    title_match = TITLE_RE.search(source)
    desc_match = DESC_RE.search(source)
    if not title_match or not desc_match:
        raise SystemExit(f"{rel}: missing <title> or <meta name=\"description\">")
    title = plain_text(title_match.group(1))
    desc = unescape(desc_match.group(1)).strip()

    canonical = rel_url(page)
    base = base_prefix(page)
    a = lambda s: escape(s, quote=True)

    lines: list[str] = [f"  {BEGIN}"]
    if is_404:
        lines.append('  <meta name="robots" content="noindex, follow">')
    else:
        lines.append('  <meta name="robots" content="index, follow, max-image-preview:large">')
        lines.append(f'  <link rel="canonical" href="{a(canonical)}">')
    lines += [
        f'  <link rel="icon" href="{base}assets/favicon.svg" type="image/svg+xml">',
        f'  <link rel="icon" href="{base}assets/favicon-32.png" sizes="32x32" type="image/png">',
        f'  <link rel="apple-touch-icon" href="{base}assets/apple-touch-icon.png">',
        f'  <link rel="manifest" href="{base}site.webmanifest">',
        '  <meta name="theme-color" content="#117346">',
        f'  <meta property="og:type" content="{"website" if is_index or is_404 else "article"}">',
        f'  <meta property="og:site_name" content="{a(SITE_NAME)}">',
        '  <meta property="og:locale" content="ja_JP">',
        f'  <meta property="og:title" content="{a(title)}">',
        f'  <meta property="og:description" content="{a(desc)}">',
        f'  <meta property="og:url" content="{a(canonical)}">',
        f'  <meta property="og:image" content="{a(OG_IMAGE)}">',
        f'  <meta property="og:image:width" content="{OG_IMAGE_W}">',
        f'  <meta property="og:image:height" content="{OG_IMAGE_H}">',
        f'  <meta property="og:image:alt" content="{a(SITE_NAME)}">',
        '  <meta name="twitter:card" content="summary_large_image">',
        f'  <meta name="twitter:title" content="{a(title)}">',
        f'  <meta name="twitter:description" content="{a(desc)}">',
        f'  <meta name="twitter:image" content="{a(OG_IMAGE)}">',
    ]
    lines += structured_data(page, source, canonical, title, desc)
    lines.append(f"  {END}")
    return "\n".join(lines)


def apply(source: str, block: str) -> str:
    source = BLOCK_RE.sub("", source)
    if "\n</head>" in source:
        return source.replace("\n</head>", "\n" + block + "\n</head>", 1)
    if "</head>" in source:
        return source.replace("</head>", block + "\n</head>", 1)
    raise SystemExit("page has no </head>")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    stale: list[str] = []
    for page in pages():
        source = page.read_text(encoding="utf-8")
        updated = apply(source, build_block(page, source))
        if updated == source:
            continue
        if args.check:
            stale.append(page.relative_to(ROOT).as_posix())
        else:
            page.write_text(updated, encoding="utf-8", newline="\n")

    if args.check:
        if stale:
            print("SEO metadata is out of date. Run build_seo.py:")
            for name in stale:
                print(f"- {name}")
            return 1
        print(f"SEO metadata is current: {len(pages())} pages.")
        return 0

    print(f"SEO metadata written: {len(pages())} pages.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
